name: deploy static web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Build Project (React, Angular, Vue)
        run: npm run build  # This should generate the 'dist' or 'build' directory

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET }} --delete  # Assuming the build directory is 'build'
